# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |

    - name: Start MySQL
      uses: samin/mysql-action@v1.3
      with:
        # The port of host
        host port: 3306
        # The port of container
        container port: 3306
        # --character-set-server - The character set of MySQL server
        character set server: 'utf8mb4'
        # --collation-server - The character collation of MySQL server
        collation server: 'utf8mb4_general_ci'
        # Version of MySQL to use
        mysql version: 'latest'
        # MYSQL_ROOT_PASSWORD - root superuser password
        mysql root password: 'roottest'
        # MYSQL_DATABASE - name for the default database that is created
        mysql database: 'roottest'
        # MYSQL_USER - create the specified user with superuser power for created database
        mysql user: 'roottest'
        # MYSQL_PASSWORD - specified superuser password which user is power for created database
        mysql password: 'roottest'
    - uses: ./.github/actions/hello
